<a href="https://colab.research.google.com/github/vidhusree/ML-Project/blob/main/Day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import numpy as pd
import seaborn as sns

In [ ]:
df=sns.load_dataset("titanic")

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [ ]:
df.count()

survived       891
pclass         891
sex            891
age            714
sibsp          891
parch          891
fare           891
embarked       889
class          891
who            891
adult_male     891
deck           203
embark_town    889
alive          891
alone          891
dtype: int64

In [ ]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [ ]:
df.shape

(891, 15)

In [ ]:
df.head(10)

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0         0       3    male  22.0      1      0   7.2500        S   Third   
1         1       1  female  38.0      1      0  71.2833        C   First   
2         1       3  female  26.0      0      0   7.9250        S   Third   
3         1       1  female  35.0      1      0  53.1000        S   First   
4         0       3    male  35.0      0      0   8.0500        S   Third   
5         0       3    male   NaN      0      0   8.4583        Q   Third   
6         0       1    male  54.0      0      0  51.8625        S   First   
7         0       3    male   2.0      3      1  21.0750        S   Third   
8         1       3  female  27.0      0      2  11.1333        S   Third   
9         1       2  female  14.0      1      0  30.0708        C  Second   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  
5    man        True  NaN   Queenstown    no   True  
6    man        True    E  Southampton    no   True  
7  child       False  NaN  Southampton    no  False  
8  woman       False  NaN  Southampton   yes  False  
9  child       False  NaN    Cherbourg   yes  False

In [ ]:
df.dtypes

survived          int64
pclass            int64
sex              object
age             float64
sibsp             int64
parch             int64
fare            float64
embarked         object
class          category
who              object
adult_male         bool
deck           category
embark_town      object
alive            object
alone              bool
dtype: object

In [ ]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [ ]:
df_clean=df.drop(columns=["deck"])
df_clean

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male  embark_town alive  alone  
0      man        True  Southampton    no  False  
1    woman       False    Cherbourg   yes  False  
2    woman       False  Southampton   yes   True  
3    woman       False  Southampton   yes  False  
4      man        True  Southampton    no   True  
..     ...         ...          ...   ...    ...  
886    man        True  Southampton    no   True  
887  woman       False  Southampton   yes   True  
888  woman       False  Southampton    no  False  
889    man        True    Cherbourg   yes   True  
890    man        True   Queenstown    no   True  

[891 rows x 14 columns]

In [ ]:
df=df.drop(columns=['deck'])
df

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male  embark_town alive  alone  
0      man        True  Southampton    no  False  
1    woman       False    Cherbourg   yes  False  
2    woman       False  Southampton   yes   True  
3    woman       False  Southampton   yes  False  
4      man        True  Southampton    no   True  
..     ...         ...          ...   ...    ...  
886    man        True  Southampton    no   True  
887  woman       False  Southampton   yes   True  
888  woman       False  Southampton    no  False  
889    man        True    Cherbourg   yes   True  
890    man        True   Queenstown    no   True  

[891 rows x 14 columns]

In [ ]:
df.shape

(891, 14)

In [ ]:
df.dropna(subset=['embarked','embark_town'],inplace=True)
print(df.isnull().sum())

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         0
class            0
who              0
adult_male       0
embark_town      0
alive            0
alone            0
dtype: int64


In [ ]:
age_mean=df['age'].mean()
df['age']=df['age'].fillna(age_mean)

In [ ]:
age_mean

np.float64(29.642092696629216)

In [ ]:
df['age_group']=np.where(df['age']<18,"child","adult")


In [ ]:
df['family_size']=df['sibsp']+df['parch']

In [ ]:
df['fare_per_person']=df['fare']/(df['family_size']+1)

In [ ]:
df.rename(columns={'pclass':'passenger_class'},inplace=True)

In [ ]:
df

survived  passenger_class     sex        age  sibsp  parch     fare  \
0           0                3    male  22.000000      1      0   7.2500   
1           1                1  female  38.000000      1      0  71.2833   
2           1                3  female  26.000000      0      0   7.9250   
3           1                1  female  35.000000      1      0  53.1000   
4           0                3    male  35.000000      0      0   8.0500   
..        ...              ...     ...        ...    ...    ...      ...   
886         0                2    male  27.000000      0      0  13.0000   
887         1                1  female  19.000000      0      0  30.0000   
888         0                3  female  29.642093      1      2  23.4500   
889         1                1    male  26.000000      0      0  30.0000   
890         0                3    male  32.000000      0      0   7.7500   

    embarked   class    who  adult_male  embark_town alive  alone age_group  \
0          S   Third    man        True  Southampton    no  False     adult   
1          C   First  woman       False    Cherbourg   yes  False     adult   
2          S   Third  woman       False  Southampton   yes   True     adult   
3          S   First  woman       False  Southampton   yes  False     adult   
4          S   Third    man        True  Southampton    no   True     adult   
..       ...     ...    ...         ...          ...   ...    ...       ...   
886        S  Second    man        True  Southampton    no   True     adult   
887        S   First  woman       False  Southampton   yes   True     adult   
888        S   Third  woman       False  Southampton    no  False     adult   
889        C   First    man        True    Cherbourg   yes   True     adult   
890        Q   Third    man        True   Queenstown    no   True     adult   

     family_size  fare_per_person  
0              1          3.62500  
1              1         35.64165  
2              0          7.92500  
3              1         26.55000  
4              0          8.05000  
..           ...              ...  
886            0         13.00000  
887            0         30.00000  
888            3          5.86250  
889            0         30.00000  
890            0          7.75000  

[889 rows x 17 columns]

In [ ]:
df[df['age']>df['age'].mean()]

survived  passenger_class     sex   age  sibsp  parch     fare embarked  \
1           1                1  female  38.0      1      0  71.2833        C   
3           1                1  female  35.0      1      0  53.1000        S   
4           0                3    male  35.0      0      0   8.0500        S   
6           0                1    male  54.0      0      0  51.8625        S   
11          1                1  female  58.0      0      0  26.5500        S   
..        ...              ...     ...   ...    ...    ...      ...      ...   
873         0                3    male  47.0      0      0   9.0000        S   
879         1                1  female  56.0      0      1  83.1583        C   
881         0                3    male  33.0      0      0   7.8958        S   
885         0                3  female  39.0      0      5  29.1250        Q   
890         0                3    male  32.0      0      0   7.7500        Q   

     class    who  adult_male  embark_town alive  alone age_group  \
1    First  woman       False    Cherbourg   yes  False     adult   
3    First  woman       False  Southampton   yes  False     adult   
4    Third    man        True  Southampton    no   True     adult   
6    First    man        True  Southampton    no   True     adult   
11   First  woman       False  Southampton   yes   True     adult   
..     ...    ...         ...          ...   ...    ...       ...   
873  Third    man        True  Southampton    no   True     adult   
879  First  woman       False    Cherbourg   yes  False     adult   
881  Third    man        True  Southampton    no   True     adult   
885  Third  woman       False   Queenstown    no  False     adult   
890  Third    man        True   Queenstown    no   True     adult   

     family_size  fare_per_person  
1              1        35.641650  
3              1        26.550000  
4              0         8.050000  
6              0        51.862500  
11             0        26.550000  
..           ...              ...  
873            0         9.000000  
879            1        41.579150  
881            0         7.895800  
885            5         4.854167  
890            0         7.750000  

[328 rows x 17 columns]

In [ ]:
df[(df['sex']=='female')&(df['passenger_class']==1)]

survived  passenger_class     sex        age  sibsp  parch      fare  \
1           1                1  female  38.000000      1      0   71.2833   
3           1                1  female  35.000000      1      0   53.1000   
11          1                1  female  58.000000      0      0   26.5500   
31          1                1  female  29.642093      1      0  146.5208   
52          1                1  female  49.000000      1      0   76.7292   
..        ...              ...     ...        ...    ...    ...       ...   
856         1                1  female  45.000000      1      1  164.8667   
862         1                1  female  48.000000      0      0   25.9292   
871         1                1  female  47.000000      1      1   52.5542   
879         1                1  female  56.000000      0      1   83.1583   
887         1                1  female  19.000000      0      0   30.0000   

    embarked  class    who  adult_male  embark_town alive  alone age_group  \
1          C  First  woman       False    Cherbourg   yes  False     adult   
3          S  First  woman       False  Southampton   yes  False     adult   
11         S  First  woman       False  Southampton   yes   True     adult   
31         C  First  woman       False    Cherbourg   yes  False     adult   
52         C  First  woman       False    Cherbourg   yes  False     adult   
..       ...    ...    ...         ...          ...   ...    ...       ...   
856        S  First  woman       False  Southampton   yes  False     adult   
862        S  First  woman       False  Southampton   yes   True     adult   
871        S  First  woman       False  Southampton   yes  False     adult   
879        C  First  woman       False    Cherbourg   yes  False     adult   
887        S  First  woman       False  Southampton   yes   True     adult   

     family_size  fare_per_person  
1              1        35.641650  
3              1        26.550000  
11             0        26.550000  
31             1        73.260400  
52             1        38.364600  
..           ...              ...  
856            2        54.955567  
862            0        25.929200  
871            2        17.518067  
879            1        41.579150  
887            0        30.000000  

[92 rows x 17 columns]

In [ ]:
df[(df['survived']==1)]

survived  passenger_class     sex   age  sibsp  parch     fare embarked  \
1           1                1  female  38.0      1      0  71.2833        C   
2           1                3  female  26.0      0      0   7.9250        S   
3           1                1  female  35.0      1      0  53.1000        S   
8           1                3  female  27.0      0      2  11.1333        S   
9           1                2  female  14.0      1      0  30.0708        C   
..        ...              ...     ...   ...    ...    ...      ...      ...   
875         1                3  female  15.0      0      0   7.2250        C   
879         1                1  female  56.0      0      1  83.1583        C   
880         1                2  female  25.0      0      1  26.0000        S   
887         1                1  female  19.0      0      0  30.0000        S   
889         1                1    male  26.0      0      0  30.0000        C   

      class    who  adult_male  embark_town alive  alone age_group  \
1     First  woman       False    Cherbourg   yes  False     adult   
2     Third  woman       False  Southampton   yes   True     adult   
3     First  woman       False  Southampton   yes  False     adult   
8     Third  woman       False  Southampton   yes  False     adult   
9    Second  child       False    Cherbourg   yes  False     child   
..      ...    ...         ...          ...   ...    ...       ...   
875   Third  child       False    Cherbourg   yes   True     child   
879   First  woman       False    Cherbourg   yes  False     adult   
880  Second  woman       False  Southampton   yes  False     adult   
887   First  woman       False  Southampton   yes   True     adult   
889   First    man        True    Cherbourg   yes   True     adult   

     family_size  fare_per_person  
1              1         35.64165  
2              0          7.92500  
3              1         26.55000  
8              2          3.71110  
9              1         15.03540  
..           ...              ...  
875            0          7.22500  
879            1         41.57915  
880            1         13.00000  
887            0         30.00000  
889            0         30.00000  

[340 rows x 17 columns]

In [ ]:
df.groupby('sex')['survived'].mean()

sex
female    0.740385
male      0.188908
Name: survived, dtype: float64

In [ ]:
df.groupby('class')['fare'].mean()

/tmp/ipython-input-4105422611.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('class')['fare'].mean()


class
First     84.193516
Second    20.662183
Third     13.675550
Name: fare, dtype: float64

In [ ]:
df.corr(numeric_only=True)

survived  passenger_class       age     sibsp     parch  \
survived         1.000000        -0.335549 -0.074513 -0.034040  0.083151   
passenger_class -0.335549         1.000000 -0.328256  0.081656  0.016824   
age             -0.074513        -0.328256  1.000000 -0.231908 -0.178013   
sibsp           -0.034040         0.081656 -0.231908  1.000000  0.414542   
parch            0.083151         0.016824 -0.178013  0.414542  1.000000   
fare             0.255290        -0.548193  0.088780  0.160887  0.217532   
adult_male      -0.555520         0.090098  0.258793 -0.255401 -0.351945   
alone           -0.206207         0.138553  0.177445 -0.584186 -0.583112   
family_size      0.018277         0.064221 -0.247459  0.890654  0.782988   
fare_per_person  0.217902        -0.482024  0.136787 -0.093211 -0.067422   

                     fare  adult_male     alone  family_size  fare_per_person  
survived         0.255290   -0.555520 -0.206207     0.018277         0.217902  
passenger_class -0.548193    0.090098  0.138553     0.064221        -0.482024  
age              0.088780    0.258793  0.177445    -0.247459         0.136787  
sibsp            0.160887   -0.255401 -0.584186     0.890654        -0.093211  
parch            0.217532   -0.351945 -0.583112     0.782988        -0.067422  
fare             1.000000   -0.179851 -0.274079     0.218658         0.840902  
adult_male      -0.179851    1.000000  0.407992    -0.350419        -0.078503  
alone           -0.274079    0.407992  1.000000    -0.690654         0.042706  
family_size      0.218658   -0.350419 -0.690654     1.000000        -0.097399  
fare_per_person  0.840902   -0.078503  0.042706    -0.097399         1.000000

In [ ]:
#2

In [ ]:
df=sns.load_dataset("tips")

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


In [ ]:
df.count()

total_bill    244
tip           244
sex           244
smoker        244
day           244
time          244
size          244
dtype: int64

In [ ]:
df.shape

(244, 7)

In [ ]:
df.size

1708

In [ ]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [ ]:
df.dtypes

total_bill     float64
tip            float64
sex           category
smoker        category
day           category
time          category
size             int64
dtype: object

In [ ]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [ ]:
df['tip'].mean()


np.float64(2.99827868852459)

In [ ]:
df['tip'].median()

2.9

In [ ]:
df['tip_percent']=(df['tip']/df['total_bill'])*100
df

total_bill   tip     sex smoker   day    time  size  tip_percent
0         16.99  1.01  Female     No   Sun  Dinner     2     5.944673
1         10.34  1.66    Male     No   Sun  Dinner     3    16.054159
2         21.01  3.50    Male     No   Sun  Dinner     3    16.658734
3         23.68  3.31    Male     No   Sun  Dinner     2    13.978041
4         24.59  3.61  Female     No   Sun  Dinner     4    14.680765
..          ...   ...     ...    ...   ...     ...   ...          ...
239       29.03  5.92    Male     No   Sat  Dinner     3    20.392697
240       27.18  2.00  Female    Yes   Sat  Dinner     2     7.358352
241       22.67  2.00    Male    Yes   Sat  Dinner     2     8.822232
242       17.82  1.75    Male     No   Sat  Dinner     2     9.820426
243       18.78  3.00  Female     No  Thur  Dinner     2    15.974441

[244 rows x 8 columns]

In [ ]:
df['high_spender']=np.where(df['total_bill']>df['total_bill'].mean(),"1","0")
df


total_bill   tip     sex smoker   day    time  size  tip_percent  \
0         16.99  1.01  Female     No   Sun  Dinner     2     5.944673   
1         10.34  1.66    Male     No   Sun  Dinner     3    16.054159   
2         21.01  3.50    Male     No   Sun  Dinner     3    16.658734   
3         23.68  3.31    Male     No   Sun  Dinner     2    13.978041   
4         24.59  3.61  Female     No   Sun  Dinner     4    14.680765   
..          ...   ...     ...    ...   ...     ...   ...          ...   
239       29.03  5.92    Male     No   Sat  Dinner     3    20.392697   
240       27.18  2.00  Female    Yes   Sat  Dinner     2     7.358352   
241       22.67  2.00    Male    Yes   Sat  Dinner     2     8.822232   
242       17.82  1.75    Male     No   Sat  Dinner     2     9.820426   
243       18.78  3.00  Female     No  Thur  Dinner     2    15.974441   

    high_spender  
0              0  
1              0  
2              1  
3              1  
4              1  
..           ...  
239            1  
240            1  
241            1  
242            0  
243            0  

[244 rows x 9 columns]

In [ ]:
df['total_bill']>30

0      False
1      False
2      False
3      False
4      False
       ...  
239    False
240    False
241    False
242    False
243    False
Name: total_bill, Length: 244, dtype: bool

In [ ]:
df['tip_percent']>20

0      False
1      False
2      False
3      False
4      False
       ...  
239     True
240    False
241    False
242    False
243    False
Name: tip_percent, Length: 244, dtype: bool

In [ ]:
df.groupby('sex')['tip'].mean()

/tmp/ipython-input-3407121299.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('sex')['tip'].mean()


sex
Male      3.089618
Female    2.833448
Name: tip, dtype: float64

In [ ]:
df.groupby('day')['total_bill'].mean()

/tmp/ipython-input-1881343769.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('day')['total_bill'].mean()


day
Thur    17.682742
Fri     17.151579
Sat     20.441379
Sun     21.410000
Name: total_bill, dtype: float64

In [ ]:
df.groupby('smoker')['tip_percent'].mean()

/tmp/ipython-input-1555110191.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('smoker')['tip_percent'].mean()


smoker
Yes    16.319604
No     15.932846
Name: tip_percent, dtype: float64

In [ ]:
df.corr(numeric_only=True)

total_bill       tip      size  tip_percent
total_bill     1.000000  0.675734  0.598315    -0.338624
tip            0.675734  1.000000  0.489299     0.342370
size           0.598315  0.489299  1.000000    -0.142860
tip_percent   -0.338624  0.342370 -0.142860     1.000000

In [ ]:
#NumPy

In [ ]:
arr1=np.arange(1,17).reshape(4,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
arr=np.arange(1,7)           #
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr[arr%2==0]=-1                #replace
arr

array([ 1, -1,  3, -1,  5, -1])

In [ ]:
arr2=np.arange(10,60,10)
arr2

array([10, 20, 30, 40, 50])

In [ ]:
mean=np.mean(arr2)
mean

np.float64(30.0)

In [ ]:
med=np.std(arr2)
med

np.float64(14.142135623730951)

In [ ]:
norm=(arr2-np.mean(arr2))/np.std(arr2)
norm

array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])

In [ ]:
arr3=np.arange(1,10).reshape(3,3)
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr3[0][1]

np.int64(2)

In [ ]:
arr3[1][1]

np.int64(5)

In [ ]:
arr3[2]

array([7, 8, 9])

In [ ]:
arr3[1:,:2]

array([[4, 5],
       [7, 8]])

In [ ]:
arr3[:2,1:]

array([[2, 3],
       [5, 6]])

In [1]:
#### 3 ####

In [5]:
df=sns.load_dataset("penguins")

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   species            344 non-null    object 
 1   island             344 non-null    object 
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object 
dtypes: float64(4), object(3)
memory usage: 18.9+ KB


In [7]:
df.count()

species              344
island               344
bill_length_mm       342
bill_depth_mm        342
flipper_length_mm    342
body_mass_g          342
sex                  333
dtype: int64

In [8]:
df.shape

(344, 7)

In [9]:
df.size

2408

In [10]:
df.columns

Index(['species', 'island', 'bill_length_mm', 'bill_depth_mm',
       'flipper_length_mm', 'body_mass_g', 'sex'],
      dtype='object')

In [11]:
df.dtypes

species               object
island                object
bill_length_mm       float64
bill_depth_mm        float64
flipper_length_mm    float64
body_mass_g          float64
sex                   object
dtype: object

In [12]:
df.isnull().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

In [13]:
df.dropna(subset=["bill_length_mm","flipper_length_mm"],inplace=True)
df

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1           18.7              181.0   
1    Adelie  Torgersen            39.5           17.4              186.0   
2    Adelie  Torgersen            40.3           18.0              195.0   
4    Adelie  Torgersen            36.7           19.3              193.0   
5    Adelie  Torgersen            39.3           20.6              190.0   
..      ...        ...             ...            ...                ...   
338  Gentoo     Biscoe            47.2           13.7              214.0   
340  Gentoo     Biscoe            46.8           14.3              215.0   
341  Gentoo     Biscoe            50.4           15.7              222.0   
342  Gentoo     Biscoe            45.2           14.8              212.0   
343  Gentoo     Biscoe            49.9           16.1              213.0   

     body_mass_g     sex  
0         3750.0    Male  
1         3800.0  Female  
2         3250.0  Female  
4         3450.0  Female  
5         3650.0    Male  
..           ...     ...  
338       4925.0  Female  
340       4850.0  Female  
341       5750.0    Male  
342       5200.0  Female  
343       5400.0    Male  

[342 rows x 7 columns]

In [15]:
bill_length_mean=df['bill_length_mm'].mean()
bill_length_mean

np.float64(43.9219298245614)

In [23]:
b=df['body_mass_g'].mean()
b

np.float64(4201.754385964912)

In [18]:
bill_length_median=df['bill_length_mm'].median()
bill_length_median

44.45

In [19]:
bill_length_median=df['body_mass_g'].median()
bill_length_median

4050.0

In [20]:
bill_depth_mean=df['bill_depth_mm'].mean()
bill_depth_mean

np.float64(17.151169590643278)

In [22]:
df['bill_depth_mm']=df['bill_depth_mm'].fillna(bill_depth_mean)
df

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1           18.7              181.0   
1    Adelie  Torgersen            39.5           17.4              186.0   
2    Adelie  Torgersen            40.3           18.0              195.0   
4    Adelie  Torgersen            36.7           19.3              193.0   
5    Adelie  Torgersen            39.3           20.6              190.0   
..      ...        ...             ...            ...                ...   
338  Gentoo     Biscoe            47.2           13.7              214.0   
340  Gentoo     Biscoe            46.8           14.3              215.0   
341  Gentoo     Biscoe            50.4           15.7              222.0   
342  Gentoo     Biscoe            45.2           14.8              212.0   
343  Gentoo     Biscoe            49.9           16.1              213.0   

     body_mass_g     sex  
0         3750.0    Male  
1         3800.0  Female  
2         3250.0  Female  
4         3450.0  Female  
5         3650.0    Male  
..           ...     ...  
338       4925.0  Female  
340       4850.0  Female  
341       5750.0    Male  
342       5200.0  Female  
343       5400.0    Male  

[342 rows x 7 columns]

In [24]:
df['bill_ratio']=df['bill_length_mm']/df['bill_depth_mm']
df

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1           18.7              181.0   
1    Adelie  Torgersen            39.5           17.4              186.0   
2    Adelie  Torgersen            40.3           18.0              195.0   
4    Adelie  Torgersen            36.7           19.3              193.0   
5    Adelie  Torgersen            39.3           20.6              190.0   
..      ...        ...             ...            ...                ...   
338  Gentoo     Biscoe            47.2           13.7              214.0   
340  Gentoo     Biscoe            46.8           14.3              215.0   
341  Gentoo     Biscoe            50.4           15.7              222.0   
342  Gentoo     Biscoe            45.2           14.8              212.0   
343  Gentoo     Biscoe            49.9           16.1              213.0   

     body_mass_g     sex  bill_ratio  
0         3750.0    Male    2.090909  
1         3800.0  Female    2.270115  
2         3250.0  Female    2.238889  
4         3450.0  Female    1.901554  
5         3650.0    Male    1.907767  
..           ...     ...         ...  
338       4925.0  Female    3.445255  
340       4850.0  Female    3.272727  
341       5750.0    Male    3.210191  
342       5200.0  Female    3.054054  
343       5400.0    Male    3.099379  

[342 rows x 8 columns]

In [25]:
df.rename(columns={'bill_length_mm':'bill_length'},inplace=True)
df

species     island  bill_length  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen         39.1           18.7              181.0   
1    Adelie  Torgersen         39.5           17.4              186.0   
2    Adelie  Torgersen         40.3           18.0              195.0   
4    Adelie  Torgersen         36.7           19.3              193.0   
5    Adelie  Torgersen         39.3           20.6              190.0   
..      ...        ...          ...            ...                ...   
338  Gentoo     Biscoe         47.2           13.7              214.0   
340  Gentoo     Biscoe         46.8           14.3              215.0   
341  Gentoo     Biscoe         50.4           15.7              222.0   
342  Gentoo     Biscoe         45.2           14.8              212.0   
343  Gentoo     Biscoe         49.9           16.1              213.0   

     body_mass_g     sex  bill_ratio  
0         3750.0    Male    2.090909  
1         3800.0  Female    2.270115  
2         3250.0  Female    2.238889  
4         3450.0  Female    1.901554  
5         3650.0    Male    1.907767  
..           ...     ...         ...  
338       4925.0  Female    3.445255  
340       4850.0  Female    3.272727  
341       5750.0    Male    3.210191  
342       5200.0  Female    3.054054  
343       5400.0    Male    3.099379  

[342 rows x 8 columns]

In [38]:
df[df['body_mass_g']>df['body_mass_g'].mean()]

species     island  bill_length  bill_depth_mm  flipper_length_mm  \
7    Adelie  Torgersen         39.2           19.6              195.0   
9    Adelie  Torgersen         42.0           20.2              190.0   
14   Adelie  Torgersen         34.6           21.1              198.0   
17   Adelie  Torgersen         42.5           20.7              197.0   
39   Adelie      Dream         39.8           19.1              184.0   
..      ...        ...          ...            ...                ...   
338  Gentoo     Biscoe         47.2           13.7              214.0   
340  Gentoo     Biscoe         46.8           14.3              215.0   
341  Gentoo     Biscoe         50.4           15.7              222.0   
342  Gentoo     Biscoe         45.2           14.8              212.0   
343  Gentoo     Biscoe         49.9           16.1              213.0   

     body_mass_g     sex  bill_ratio  
7         4675.0    Male    2.000000  
9         4250.0     NaN    2.079208  
14        4400.0    Male    1.639810  
17        4500.0    Male    2.053140  
39        4650.0    Male    2.083770  
..           ...     ...         ...  
338       4925.0  Female    3.445255  
340       4850.0  Female    3.272727  
341       5750.0    Male    3.210191  
342       5200.0  Female    3.054054  
343       5400.0    Male    3.099379  

[149 rows x 8 columns]

In [33]:
df[(df['sex']=='Female')&(df['flipper_length_mm']>200)]


species  island  bill_length  bill_depth_mm  flipper_length_mm  \
90      Adelie   Dream         35.7           18.0              202.0   
216  Chinstrap   Dream         43.5           18.1              202.0   
220     Gentoo  Biscoe         46.1           13.2              211.0   
222     Gentoo  Biscoe         48.7           14.1              210.0   
225     Gentoo  Biscoe         46.5           13.5              210.0   
226     Gentoo  Biscoe         45.4           14.6              211.0   
228     Gentoo  Biscoe         43.3           13.4              209.0   
230     Gentoo  Biscoe         40.9           13.7              214.0   
232     Gentoo  Biscoe         45.5           13.7              214.0   
234     Gentoo  Biscoe         45.8           14.6              210.0   
236     Gentoo  Biscoe         42.0           13.5              210.0   
238     Gentoo  Biscoe         46.2           14.5              209.0   
241     Gentoo  Biscoe         45.1           14.5              215.0   
242     Gentoo  Biscoe         46.5           14.5              213.0   
244     Gentoo  Biscoe         42.9           13.1              215.0   
248     Gentoo  Biscoe         48.2           14.3              210.0   
251     Gentoo  Biscoe         42.8           14.2              209.0   
252     Gentoo  Biscoe         45.1           14.5              207.0   
254     Gentoo  Biscoe         49.1           14.8              220.0   
256     Gentoo  Biscoe         42.6           13.7              213.0   
258     Gentoo  Biscoe         44.0           13.6              208.0   
260     Gentoo  Biscoe         42.7           13.7              208.0   
262     Gentoo  Biscoe         45.3           13.7              210.0   
265     Gentoo  Biscoe         43.6           13.9              217.0   
266     Gentoo  Biscoe         45.5           13.9              210.0   
268     Gentoo  Biscoe         44.9           13.3              213.0   
270     Gentoo  Biscoe         46.6           14.2              210.0   
272     Gentoo  Biscoe         45.1           14.4              210.0   
274     Gentoo  Biscoe         46.5           14.4              217.0   
276     Gentoo  Biscoe         43.8           13.9              208.0   
278     Gentoo  Biscoe         43.2           14.5              208.0   
280     Gentoo  Biscoe         45.3           13.8              208.0   
282     Gentoo  Biscoe         45.7           13.9              214.0   
284     Gentoo  Biscoe         45.8           14.2              219.0   
288     Gentoo  Biscoe         43.5           14.2              220.0   
290     Gentoo  Biscoe         47.7           15.0              216.0   
293     Gentoo  Biscoe         46.5           14.8              217.0   
294     Gentoo  Biscoe         46.4           15.0              216.0   
296     Gentoo  Biscoe         47.5           14.2              209.0   
298     Gentoo  Biscoe         45.2           13.8              215.0   
300     Gentoo  Biscoe         49.1           14.5              212.0   
302     Gentoo  Biscoe         47.4           14.6              212.0   
304     Gentoo  Biscoe         44.9           13.8              212.0   
306     Gentoo  Biscoe         43.4           14.4              218.0   
308     Gentoo  Biscoe         47.5           14.0              212.0   
310     Gentoo  Biscoe         47.5           15.0              218.0   
312     Gentoo  Biscoe         45.5           14.5              212.0   
314     Gentoo  Biscoe         44.5           14.7              214.0   
317     Gentoo  Biscoe         46.9           14.6              222.0   
318     Gentoo  Biscoe         48.4           14.4              203.0   
320     Gentoo  Biscoe         48.5           15.0              219.0   
322     Gentoo  Biscoe         47.2           15.5              215.0   
326     Gentoo  Biscoe         41.7           14.7              210.0   
328     Gentoo  Biscoe         43.3           14.0              2

In [34]:
df.groupby('sex')['bill_ratio'].mean()

sex
Female    2.609508
Male      2.604988
Name: bill_ratio, dtype: float64

In [36]:
df.groupby('species')['flipper_length_mm'].mean()

species
Adelie       189.953642
Chinstrap    195.823529
Gentoo       217.186992
Name: flipper_length_mm, dtype: float64

In [37]:
df.corr(numeric_only=True)

bill_length  bill_depth_mm  flipper_length_mm  body_mass_g  \
bill_length           1.000000      -0.235053           0.656181     0.595110   
bill_depth_mm        -0.235053       1.000000          -0.583851    -0.471916   
flipper_length_mm     0.656181      -0.583851           1.000000     0.871202   
body_mass_g           0.595110      -0.471916           0.871202     1.000000   
bill_ratio            0.780396      -0.784191           0.805166     0.703119   

                   bill_ratio  
bill_length          0.780396  
bill_depth_mm       -0.784191  
flipper_length_mm    0.805166  
body_mass_g          0.703119  
bill_ratio           1.000000